name: test

on:
  - push

jobs:
  test:
    runs-on: ${{ matrix.hostos }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux_x64
            hostos: ubuntu-latest
          - target: linux_arm64
            hostos: ubuntu-latest
          - target: macos_x64
            hostos: macos-latest
          - target: macos_arm64
            hostos: macos-latest
          - target: windows_x64
            hostos: ubuntu-latest
          - target: windows_arm64
            hostos: ubuntu-latest
          - target: linux_x64_musl
            hostos: ubuntu-latest
          - target: linux_arm64_musl
            hostos: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 2.2.x
          nim-install-directory: nim
          parent-nim-install-directory: /opt
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install
      - run: nimble '${{ matrix.target }}' --verbose
      - run: ls -al
      - uses: actions/upload-artifact@v4
        with:
          name: cross_${{ matrix.target }}
          path: cross_${{ matrix.target }}
      - run: file './cross_${{ matrix.target }}'
      - run: objdump -f './cross_${{ matrix.target }}' || true
      - run: objdump -h './cross_${{ matrix.target }}' || true
      - run: objdump -p './cross_${{ matrix.target }}' || true
      - run: readelf -h './cross_${{ matrix.target }}' || true
      - run: ldd './cross_${{ matrix.target }}' || true
      - run: strings './cross_${{ matrix.target }}' | head -20 || true
